framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'noreply@conagrivet.it'
        headers:
            from: 'CONAGRIVET <noreply@conagrivet.it>'
            bcc: 'Ettore Del Negro <ettore@themecraft.studio>'


