framework:
    workflows:
        task:
            type: 'workflow'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Task
            initial_marking: tentative
            places:
                - tentative
                - scheduled
#                - executed
#                - settled
            transitions:
                schedule:
                    from: [tentative]
                    to: [scheduled]

