api:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: '/api/v1'
    name_prefix: 'api.1_'
    stateless: true

frontend:
    # '*' avoids recurse inside subdirectories
    resource: ../../src/Controller/*
    type: annotation
    stateless: false

kernel:
    resource: ../../src/Kernel.php
    type: annotation
